### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SamGuay** [clemcou-socio/23Rcode#1]
Afin d'assurer que les gens peuvent utiliser le code, il faudrait ajouter une license. 

[CC-BY](https://creativecommons.org/licenses/by/4.0/)?

**Comment by clemcou-socio** [comment]
Oui ce serait une bonne idée, comment on fait ça? 
En passant, on préfère communiquer par Trello. Aussi on attendait ta réponse pour une réunion cette semaine, aurais-tu des disponibilités?

**Comment by clemcou-socio** [comment]
Est-ce que ce qu'on écrit dans Issues est visible au public?

**Comment by SamGuay** [comment]
Closing this because #2
